
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf0c\xe4%\xc9p,\xcc)\xfb9g\xc0\xa0P\xd5'
    
_lr_action_items = {'RPAREN':([1,4,9,10,11,12,13,],[-5,9,-6,-1,-4,-2,-3,]),'DIVIDE':([1,3,4,9,10,11,12,13,],[-5,6,6,-6,6,6,6,6,]),'NUMBER':([0,2,5,6,7,8,],[1,1,1,1,1,1,]),'TIMES':([1,3,4,9,10,11,12,13,],[-5,8,8,-6,8,8,8,8,]),'PLUS':([1,3,4,9,10,11,12,13,],[-5,5,5,-6,5,5,5,5,]),'LPAREN':([0,2,5,6,7,8,],[2,2,2,2,2,2,]),'MINUS':([1,3,4,9,10,11,12,13,],[-5,7,7,-6,7,7,7,7,]),'$end':([1,3,9,10,11,12,13,],[-5,0,-6,-1,-4,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,7,8,],[3,4,10,11,12,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','d:\\Python_Proj\\lex-yacc.py',9),
  ('expression -> expression MINUS expression','expression',3,'p_expression_plus','d:\\Python_Proj\\lex-yacc.py',10),
  ('expression -> expression TIMES expression','expression',3,'p_expression_plus','d:\\Python_Proj\\lex-yacc.py',11),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_plus','d:\\Python_Proj\\lex-yacc.py',12),
  ('expression -> NUMBER','expression',1,'p_expression_num','d:\\Python_Proj\\lex-yacc.py',16),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_lfparenthesis','d:\\Python_Proj\\lex-yacc.py',19),
  ('header -> HEADER LBRACE list_expression RBRACE','header',4,'p_expression_head','d:\\Python_Proj\\lex-yacc.py',23),
  ('list_expression -> list_expression NAME','list_expression',2,'p_list_expression','d:\\Python_Proj\\lex-yacc.py',27),
  ('list_expression -> NAME','list_expression',1,'p_list_expression','d:\\Python_Proj\\lex-yacc.py',28),
]
